"""
The final, honest, held-out test set for evaluating the judge model after
adding rat_fraud to training -- built deliberately separate from every other
file in this pipeline, with explicit leak checks, not just "different seed
and hope for the best."

Why a NEW test file instead of reusing synthetic_test_v2.csv (the companion
test file generate_dataset.py already produces) or synthetic_rat_fraud_test.csv
(from generate_ato_rat_test.py):
  - synthetic_test_v2.csv was generated by the SAME __main__ block as the
    training file, using seed=1337. Fine in principle, but user IDs there
    also start from user_0 (make_user_baseline numbers from 0 regardless of
    seed) -- an ID-namespace collision with the training file's user_0..599,
    flagged earlier in this project as sloppy-but-harmless (the code never
    concatenates the two files, so it never caused a real leak) but worth
    not repeating here, now that we're being asked explicitly to "ensure no
    leakage."
  - synthetic_rat_fraud_test.csv was used to DESIGN and validate the
    rat_fraud persona's shape before it existed as a training persona --
    reusing it now that rat_fraud IS a training persona would test the
    model on the exact file used to prototype the pattern it just trained
    on. Not the same file, but too close in spirit for an honest final
    check.

This file:
  1. Uses explicit ID namespacing (user_id starts at 100000) so there is
     zero possible confusion with training's user_0..599, even under manual
     inspection of the raw CSV -- not just "the code happens not to mix
     them."
  2. Uses a seed (90210) and a date range (2026-01-01 onward) disjoint from
     every other generator call in this project.
  3. Includes ALL SIX personas (not just rat_fraud) at realistic relative
     rates, so this is a genuine end-to-end evaluation of the retrained
     judge, not a narrow single-pattern check.
  4. Runs an explicit, printed leak check at the end: zero user_id overlap
     with synthetic_train_v2.csv, confirmed by set intersection, not
     assumed.
"""
import numpy as np
import pandas as pd
from datetime import datetime, timedelta

from generate_dataset import (
    DEVICE_TYPES, SCREEN_SIZES, BROWSERS, LANGUAGES, ORIENTATIONS, CITIES,
    sample_normal_session, sample_anomalous_session,
)

USER_ID_OFFSET = 100_000  # disjoint namespace from training's user_0..599


def make_user_baseline_offset(rng: np.random.Generator, user_idx: int):
    """Identical to generate_dataset.make_user_baseline, except the user_id
    is drawn from a namespace that cannot collide with training data, even
    by coincidence."""
    device_type = rng.choice(DEVICE_TYPES, p=[0.55, 0.35, 0.10])
    return {
        'user_id': f'user_{USER_ID_OFFSET + user_idx}',
        'device_type': device_type,
        'screen_size': rng.choice(SCREEN_SIZES[device_type]),
        'browser_info': rng.choice(BROWSERS),
        'language': rng.choice(LANGUAGES, p=[0.7, 0.2, 0.1]),
        'timezone_offset': -330,
        'home_city': rng.choice(CITIES),
        'usual_hour_center': rng.integers(8, 22),
        'typing_speed_mult': rng.uniform(0.7, 1.3),
        'avg_session_len': rng.integers(45, 240),
        'avg_txn_amount': rng.uniform(200, 8000),
    }


def generate_final_test(n_users=250, sessions_per_user=8, anomaly_rate=0.018, seed=90210,
                         start_date='2026-01-01'):
    rng = np.random.default_rng(seed)
    users = [make_user_baseline_offset(rng, i) for i in range(n_users)]
    base_date = datetime.fromisoformat(start_date)

    rows = []
    session_counter = 0
    for user in users:
        for _ in range(sessions_per_user):
            session_counter += 1
            day_offset = int(rng.integers(0, 120))
            sess_date = base_date + timedelta(days=day_offset)
            if rng.random() < anomaly_rate:
                row = sample_anomalous_session(rng, user, session_counter, sess_date)
                row['label'] = 1
            else:
                row = sample_normal_session(rng, user, session_counter, sess_date)
            rows.append(row)

    df = pd.DataFrame(rows).sample(frac=1, random_state=seed).reset_index(drop=True)
    return df


if __name__ == '__main__':
    df = generate_final_test()
    df.to_csv('synthetic_final_honest_test.csv', index=False)

    print(f"Final honest test set: {len(df)} rows, {df['label'].sum()} anomalies "
          f"({df['label'].mean()*100:.2f}%)")
    print(df['persona'].value_counts())
    print()

    # --- Explicit leak checks, not assumed ---
    train_df = pd.read_csv('synthetic_train_v2.csv')
    train_users = set(train_df['user_id'])
    test_users = set(df['user_id'])
    overlap = train_users & test_users
    print(f"Leak check 1 -- user_id overlap with synthetic_train_v2.csv: {len(overlap)} shared users "
          f"({'PASS' if len(overlap) == 0 else 'FAIL'})")

    train_dates = pd.to_datetime(train_df['transaction_date'])
    test_dates = pd.to_datetime(df['transaction_date'])
    print(f"Leak check 2 -- date range separation: "
          f"train=[{train_dates.min()} .. {train_dates.max()}], "
          f"test=[{test_dates.min()} .. {test_dates.max()}] "
          f"({'PASS -- no overlap' if test_dates.min() > train_dates.max() else 'CHECK MANUALLY'})")

    # Row-level exact-duplicate check (same feature values appearing in both
    # files would be suspicious regardless of user_id/date, e.g. a copy-paste
    # bug in the generator)
    feat_cols = ['device_type', 'click_events', 'scroll_events', 'touch_events', 'keyboard_events',
                 'device_motion', 'time_on_page', 'screen_size', 'browser_info', 'transaction_amount',
                 'mouse_movement']
    train_tuples = set(map(tuple, train_df[feat_cols].values))
    test_tuples = set(map(tuple, df[feat_cols].values))
    row_overlap = train_tuples & test_tuples
    print(f"Leak check 3 -- exact feature-row duplicates between train and test: {len(row_overlap)} "
          f"({'PASS' if len(row_overlap) == 0 else 'FAIL'})")
